# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPVReplaceForm.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(238, 203)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Text = QtWidgets.QWidget()
        self.Text.setObjectName("Text")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Text)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.Text)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.Find = QtWidgets.QLineEdit(self.Text)
        self.Find.setObjectName("Find")
        self.verticalLayout_8.addWidget(self.Find)
        self.label_2 = QtWidgets.QLabel(self.Text)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.Replace = QtWidgets.QLineEdit(self.Text)
        self.Replace.setObjectName("Replace")
        self.verticalLayout_8.addWidget(self.Replace)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.Group = QtWidgets.QCheckBox(self.Text)
        self.Group.setObjectName("Group")
        self.verticalLayout_8.addWidget(self.Group)
        self.Regex = QtWidgets.QCheckBox(self.Text)
        self.Regex.setObjectName("Regex")
        self.verticalLayout_8.addWidget(self.Regex)
        self.tabWidget.addTab(self.Text, "")
        self.Color = QtWidgets.QWidget()
        self.Color.setObjectName("Color")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Color)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ColorLayout = QtWidgets.QVBoxLayout()
        self.ColorLayout.setSpacing(4)
        self.ColorLayout.setObjectName("ColorLayout")
        self.label_3 = QtWidgets.QLabel(self.Color)
        self.label_3.setObjectName("label_3")
        self.ColorLayout.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(self.Color)
        self.widget.setStyleSheet("QWidget#widget {border : 1px solid rgb(181, 181, 181)}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ColorFind = QtWidgets.QPushButton(self.widget)
        self.ColorFind.setMinimumSize(QtCore.QSize(25, 25))
        self.ColorFind.setMaximumSize(QtCore.QSize(25, 25))
        self.ColorFind.setStyleSheet("background-color: rgb(199, 199, 199); border : none;")
        self.ColorFind.setText("")
        self.ColorFind.setObjectName("ColorFind")
        self.horizontalLayout_4.addWidget(self.ColorFind)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ToleranceLabel = QtWidgets.QLabel(self.widget)
        self.ToleranceLabel.setObjectName("ToleranceLabel")
        self.verticalLayout_2.addWidget(self.ToleranceLabel)
        self.ColorTolerance = QtWidgets.QDoubleSpinBox(self.widget)
        self.ColorTolerance.setMaximum(300.0)
        self.ColorTolerance.setObjectName("ColorTolerance")
        self.verticalLayout_2.addWidget(self.ColorTolerance)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AlphaEnable = QtWidgets.QCheckBox(self.widget)
        self.AlphaEnable.setObjectName("AlphaEnable")
        self.verticalLayout_4.addWidget(self.AlphaEnable)
        self.AlphaFind = QtWidgets.QDoubleSpinBox(self.widget)
        self.AlphaFind.setDecimals(3)
        self.AlphaFind.setMaximum(1.0)
        self.AlphaFind.setSingleStep(0.01)
        self.AlphaFind.setObjectName("AlphaFind")
        self.verticalLayout_4.addWidget(self.AlphaFind)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.ColorLayout.addWidget(self.widget)
        self.label_5 = QtWidgets.QLabel(self.Color)
        self.label_5.setObjectName("label_5")
        self.ColorLayout.addWidget(self.label_5)
        self.widget_2 = QtWidgets.QWidget(self.Color)
        self.widget_2.setStyleSheet("QWidget#widget_2 {border : 1px solid rgb(181, 181, 181)}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ColorFind_2 = QtWidgets.QPushButton(self.widget_2)
        self.ColorFind_2.setMinimumSize(QtCore.QSize(25, 25))
        self.ColorFind_2.setMaximumSize(QtCore.QSize(25, 25))
        self.ColorFind_2.setStyleSheet("background-color:rgb(206, 206, 206);border:none;")
        self.ColorFind_2.setText("")
        self.ColorFind_2.setObjectName("ColorFind_2")
        self.horizontalLayout_2.addWidget(self.ColorFind_2)
        spacerItem2 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.AlphaReplace = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.AlphaReplace.setDecimals(3)
        self.AlphaReplace.setMaximum(1.0)
        self.AlphaReplace.setSingleStep(0.01)
        self.AlphaReplace.setObjectName("AlphaReplace")
        self.verticalLayout_5.addWidget(self.AlphaReplace)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.ColorLayout.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 500000000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ColorLayout.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.ColorLayout)
        spacerItem4 = QtWidgets.QSpacerItem(1000000000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.Color, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Find what:"))
        self.label_2.setText(_translate("Form", "Replace with:"))
        self.Group.setText(_translate("Form", "Apply to Path Groups (\\n separator)"))
        self.Regex.setText(_translate("Form", "Use Python Regex"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Text), _translate("Form", "Text"))
        self.label_3.setText(_translate("Form", "Find Color:"))
        self.ToleranceLabel.setText(_translate("Form", "Tolerance"))
        self.AlphaEnable.setText(_translate("Form", "Alpha"))
        self.label_5.setText(_translate("Form", "Replace with:"))
        self.label_4.setText(_translate("Form", "Alpha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Color), _translate("Form", "Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

