# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPVSlot.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(296, 41)
        Form.setMinimumSize(QtCore.QSize(0, 40))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.efxslot = QtWidgets.QSpinBox(Form)
        self.efxslot.setMaximum(255)
        self.efxslot.setObjectName("efxslot")
        self.verticalLayout.addWidget(self.efxslot)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.colorTool = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorTool.sizePolicy().hasHeightForWidth())
        self.colorTool.setSizePolicy(sizePolicy)
        self.colorTool.setText("")
        self.colorTool.setObjectName("colorTool")
        self.verticalLayout_2.addWidget(self.colorTool)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.alpha = QtWidgets.QSpinBox(Form)
        self.alpha.setMaximum(255)
        self.alpha.setObjectName("alpha")
        self.verticalLayout_6.addWidget(self.alpha)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.saturation = QtWidgets.QDoubleSpinBox(Form)
        self.saturation.setDecimals(3)
        self.saturation.setMinimum(-99.99)
        self.saturation.setSingleStep(0.001)
        self.saturation.setProperty("value", 1.0)
        self.saturation.setObjectName("saturation")
        self.verticalLayout_3.addWidget(self.saturation)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.size = QtWidgets.QSpinBox(Form)
        self.size.setMinimum(-2147483648)
        self.size.setMaximum(2147483647)
        self.size.setProperty("value", 0)
        self.size.setObjectName("size")
        self.verticalLayout_4.addWidget(self.size)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.frequency = QtWidgets.QDoubleSpinBox(Form)
        self.frequency.setDecimals(3)
        self.frequency.setMinimum(-99.99)
        self.frequency.setProperty("value", 1.0)
        self.frequency.setObjectName("frequency")
        self.verticalLayout_5.addWidget(self.frequency)
        self.horizontalLayout.addLayout(self.verticalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "EFX Slot"))
        self.label_2.setText(_translate("Form", "Color"))
        self.label_6.setText(_translate("Form", "Alpha"))
        self.label_3.setText(_translate("Form", "Saturation"))
        self.label_4.setText(_translate("Form", "Size"))
        self.label_5.setText(_translate("Form", "Frequency"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

