# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.fileTabs.setMovable(True)
        self.fileTabs.setObjectName("fileTabs")
        self.verticalLayout_4.addWidget(self.fileTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuScripting = QtWidgets.QMenu(self.menubar)
        self.menuScripting.setObjectName("menuScripting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRun_Code = QtWidgets.QAction(MainWindow)
        self.actionRun_Code.setObjectName("actionRun_Code")
        self.actionExport_Json = QtWidgets.QAction(MainWindow)
        self.actionExport_Json.setObjectName("actionExport_Json")
        self.actionFile_Scripting = QtWidgets.QAction(MainWindow)
        self.actionFile_Scripting.setObjectName("actionFile_Scripting")
        self.actionMultifile_Scripting = QtWidgets.QAction(MainWindow)
        self.actionMultifile_Scripting.setObjectName("actionMultifile_Scripting")
        self.actionAsterisk_Scripts = QtWidgets.QAction(MainWindow)
        self.actionAsterisk_Scripts.setObjectName("actionAsterisk_Scripts")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSave_All = QtWidgets.QAction(MainWindow)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionScripting = QtWidgets.QAction(MainWindow)
        self.actionScripting.setObjectName("actionScripting")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy_Properties = QtWidgets.QAction(MainWindow)
        self.actionCopy_Properties.setObjectName("actionCopy_Properties")
        self.actionPaste_Properties = QtWidgets.QAction(MainWindow)
        self.actionPaste_Properties.setObjectName("actionPaste_Properties")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_Next = QtWidgets.QAction(MainWindow)
        self.actionFind_Next.setObjectName("actionFind_Next")
        self.actionBatch_Replace = QtWidgets.QAction(MainWindow)
        self.actionBatch_Replace.setObjectName("actionBatch_Replace")
        self.actionDuplicate = QtWidgets.QAction(MainWindow)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.actionPush_To_Copy_Stack = QtWidgets.QAction(MainWindow)
        self.actionPush_To_Copy_Stack.setObjectName("actionPush_To_Copy_Stack")
        self.actionPop_Copy_Stack = QtWidgets.QAction(MainWindow)
        self.actionPop_Copy_Stack.setObjectName("actionPop_Copy_Stack")
        self.actionPaste_Copy_Stack = QtWidgets.QAction(MainWindow)
        self.actionPaste_Copy_Stack.setObjectName("actionPaste_Copy_Stack")
        self.actionClear_Copy_Stack = QtWidgets.QAction(MainWindow)
        self.actionClear_Copy_Stack.setObjectName("actionClear_Copy_Stack")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionCopy_Stack = QtWidgets.QAction(MainWindow)
        self.actionCopy_Stack.setObjectName("actionCopy_Stack")
        self.actionNew_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionNew_Group = QtWidgets.QAction(MainWindow)
        self.actionNew_Group.setObjectName("actionNew_Group")
        self.actionNew_Record = QtWidgets.QAction(MainWindow)
        self.actionNew_Record.setObjectName("actionNew_Record")
        self.menuOpen.addAction(self.actionNew)
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionSave_As)
        self.menuOpen.addAction(self.actionSave_All)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionCopy_Properties)
        self.menuEdit.addAction(self.actionPaste_Properties)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPush_To_Copy_Stack)
        self.menuEdit.addAction(self.actionPaste_Copy_Stack)
        self.menuEdit.addAction(self.actionClear_Copy_Stack)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionNew_Group)
        self.menuEdit.addAction(self.actionNew_Record)
        self.menuScripting.addAction(self.actionFile_Scripting)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionScripting)
        self.menuSearch.addAction(self.actionFind)
        self.menuSearch.addAction(self.actionReplace)
        self.menuSearch.addAction(self.actionBatch_Replace)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuScripting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.fileTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuScripting.setTitle(_translate("MainWindow", "Scripting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRun_Code.setText(_translate("MainWindow", "Mass Map Colors"))
        self.actionExport_Json.setText(_translate("MainWindow", "Export Json (Ctrl+Alt+Shift+S)"))
        self.actionExport_Json.setShortcut(_translate("MainWindow", "Ctrl+Alt+Shift+S"))
        self.actionFile_Scripting.setText(_translate("MainWindow", "Load Script"))
        self.actionMultifile_Scripting.setText(_translate("MainWindow", "Load Safe Script"))
        self.actionAsterisk_Scripts.setText(_translate("MainWindow", "Asterisk\'s Scripts"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionSave_All.setText(_translate("MainWindow", "Save All"))
        self.actionSave_All.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionScripting.setText(_translate("MainWindow", "Scripting"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionCopy_Properties.setText(_translate("MainWindow", "Copy Properties"))
        self.actionCopy_Properties.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionPaste_Properties.setText(_translate("MainWindow", "Paste Properties"))
        self.actionPaste_Properties.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionReplace.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFind_Next.setText(_translate("MainWindow", "Find Next"))
        self.actionFind_Next.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionBatch_Replace.setText(_translate("MainWindow", "Batch Replace"))
        self.actionBatch_Replace.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionDuplicate.setText(_translate("MainWindow", "Duplicate"))
        self.actionDuplicate.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPush_To_Copy_Stack.setText(_translate("MainWindow", "Push To Copy Stack"))
        self.actionPush_To_Copy_Stack.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.actionPop_Copy_Stack.setText(_translate("MainWindow", "Pop Copy Stack"))
        self.actionPaste_Copy_Stack.setText(_translate("MainWindow", "Paste Copy Stack"))
        self.actionPaste_Copy_Stack.setShortcut(_translate("MainWindow", "Ctrl+Alt+V"))
        self.actionClear_Copy_Stack.setText(_translate("MainWindow", "Clear Copy Stack"))
        self.actionClear_Copy_Stack.setShortcut(_translate("MainWindow", "Ctrl+Alt+Z"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionCopy_Stack.setText(_translate("MainWindow", "Copy Stack"))
        self.actionNew_2.setText(_translate("MainWindow", "New Entry"))
        self.actionNew_Group.setText(_translate("MainWindow", "New Group"))
        self.actionNew_Group.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionNew_Record.setText(_translate("MainWindow", "New Record"))
        self.actionNew_Record.setShortcut(_translate("MainWindow", "Ctrl+Alt+N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

